# Generated by Django 4.2.4 on 2023-09-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0002_post_statement_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="statement_order",
            new_name="post_order",
        ),
    ]
