# Generated by Django 4.2.4 on 2023-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0003_rename_statement_order_post_post_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="statement_order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
